#!/bin/bash

year=2022

day=$(date +%-d)
dir=day$day

cargo new $dir
curl -b $(cat ~/aoc_cookie) "https://adventofcode.com/$year/day/$day/input" \
     > $dir/input
xclip -selection primary -o > $dir/sample

echo 'advent22 = { path = "../" }' >> $dir/Cargo.toml
sed  -i "/members/a\"$dir\"," Cargo.toml
sed -i '1i use advent22::*;' $dir/src/main.rs

touch $dir/.projectile
emacsclient -n -r $dir/src/main.rs
firefox -P stream "https://adventofcode.com/2022/day/$day"
